# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"  # Triggers PATCH release
    open-pull-requests-limit: 10
    groups:
      lsd-dependencies:
        patterns:
          - "io.github.lsd-consulting:*"
        update-types:
          - "minor"
          - "patch"

      gcp-dependencies:
        patterns:
          - "com.google.cloud:*"
        update-types:
          - "minor"
          - "patch"

      spring-dependencies:
        patterns:
          - "org.springframework.*:*"
          - "org.springframework.cloud:*"
        update-types:
          - "minor"
          - "patch"

      jackson-dependencies:
        patterns:
          - "com.fasterxml.jackson.*:*"
        update-types:
          - "minor"
          - "patch"

      utility-dependencies:
        patterns:
          - "org.slf4j:*"
        update-types:
          - "minor"
          - "patch"

      kotlin-dependencies:
        patterns:
          - "org.jetbrains.kotlin*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"  # For workflow updates - no version impact
